// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ahsanullah_test
Rcpp::NumericVector ahsanullah_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_ahsanullah_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ahsanullah_test(x));
    return rcpp_result_gen;
END_RCPP
}
// atkinson_test
Rcpp::NumericVector atkinson_test(Rcpp::NumericVector x, double p);
RcppExport SEXP exptest2_atkinson_test(SEXP xSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(atkinson_test(x, p));
    return rcpp_result_gen;
END_RCPP
}
// co_test
Rcpp::NumericVector co_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_co_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(co_test(x));
    return rcpp_result_gen;
END_RCPP
}
// cvm_test
Rcpp::NumericVector cvm_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_cvm_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cvm_test(x));
    return rcpp_result_gen;
END_RCPP
}
// deshpande_test
Rcpp::NumericVector deshpande_test(Rcpp::NumericVector x, double b);
RcppExport SEXP exptest2_deshpande_test(SEXP xSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(deshpande_test(x, b));
    return rcpp_result_gen;
END_RCPP
}
// ep_test
Rcpp::NumericVector ep_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_ep_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ep_test(x));
    return rcpp_result_gen;
END_RCPP
}
// epstein_test
Rcpp::NumericVector epstein_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_epstein_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(epstein_test(x));
    return rcpp_result_gen;
END_RCPP
}
// frozini_test
Rcpp::NumericVector frozini_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_frozini_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(frozini_test(x));
    return rcpp_result_gen;
END_RCPP
}
// gini_test
Rcpp::NumericVector gini_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_gini_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(gini_test(x));
    return rcpp_result_gen;
END_RCPP
}
// gnedenko_test
Rcpp::NumericVector gnedenko_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_gnedenko_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(gnedenko_test(x));
    return rcpp_result_gen;
END_RCPP
}
// harris_test
Rcpp::NumericVector harris_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_harris_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(harris_test(x));
    return rcpp_result_gen;
END_RCPP
}
// hegazy1_test
Rcpp::NumericVector hegazy1_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_hegazy1_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(hegazy1_test(x));
    return rcpp_result_gen;
END_RCPP
}
// hegazy2_test
Rcpp::NumericVector hegazy2_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_hegazy2_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(hegazy2_test(x));
    return rcpp_result_gen;
END_RCPP
}
// hollander_test
Rcpp::NumericVector hollander_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_hollander_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(hollander_test(x));
    return rcpp_result_gen;
END_RCPP
}
// integral_test
Rcpp::NumericVector integral_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_integral_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(integral_test(x));
    return rcpp_result_gen;
END_RCPP
}
// kimber_test
Rcpp::NumericVector kimber_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_kimber_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(kimber_test(x));
    return rcpp_result_gen;
END_RCPP
}
// kochar_test
Rcpp::NumericVector kochar_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_kochar_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(kochar_test(x));
    return rcpp_result_gen;
END_RCPP
}
// kolmogorov_test
Rcpp::NumericVector kolmogorov_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_kolmogorov_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(kolmogorov_test(x));
    return rcpp_result_gen;
END_RCPP
}
// ks_test
Rcpp::NumericVector ks_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_ks_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ks_test(x));
    return rcpp_result_gen;
END_RCPP
}
// lorenz_test
Rcpp::NumericVector lorenz_test(Rcpp::NumericVector x, double p);
RcppExport SEXP exptest2_lorenz_test(SEXP xSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(lorenz_test(x, p));
    return rcpp_result_gen;
END_RCPP
}
// moran_test
Rcpp::NumericVector moran_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_moran_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(moran_test(x));
    return rcpp_result_gen;
END_RCPP
}
// pietra_test
Rcpp::NumericVector pietra_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_pietra_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pietra_test(x));
    return rcpp_result_gen;
END_RCPP
}
// rossberg_test
Rcpp::NumericVector rossberg_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_rossberg_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rossberg_test(x));
    return rcpp_result_gen;
END_RCPP
}
// shapiro_test
Rcpp::NumericVector shapiro_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_shapiro_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shapiro_test(x));
    return rcpp_result_gen;
END_RCPP
}
// we_test
Rcpp::NumericVector we_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_we_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(we_test(x));
    return rcpp_result_gen;
END_RCPP
}
// ww_test
Rcpp::NumericVector ww_test(Rcpp::NumericVector x);
RcppExport SEXP exptest2_ww_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ww_test(x));
    return rcpp_result_gen;
END_RCPP
}
