# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ahsanullah_test <- function(x) {
    .Call(`_exptest2_ahsanullah_test`, x)
}

atkinson_test <- function(x, p = 0.99) {
    .Call(`_exptest2_atkinson_test`, x, p)
}

co_test <- function(x) {
    .Call(`_exptest2_co_test`, x)
}

cvm_test <- function(x) {
    .Call(`_exptest2_cvm_test`, x)
}

deshpande_test <- function(x, b = 0.44) {
    .Call(`_exptest2_deshpande_test`, x, b)
}

ep_test <- function(x) {
    .Call(`_exptest2_ep_test`, x)
}

epstein_test <- function(x) {
    .Call(`_exptest2_epstein_test`, x)
}

frozini_test <- function(x) {
    .Call(`_exptest2_frozini_test`, x)
}

gini_test <- function(x) {
    .Call(`_exptest2_gini_test`, x)
}

gnedenko_test <- function(x) {
    .Call(`_exptest2_gnedenko_test`, x)
}

harris_test <- function(x) {
    .Call(`_exptest2_harris_test`, x)
}

hegazy1_test <- function(x) {
    .Call(`_exptest2_hegazy1_test`, x)
}

hegazy2_test <- function(x) {
    .Call(`_exptest2_hegazy2_test`, x)
}

hollander_test <- function(x) {
    .Call(`_exptest2_hollander_test`, x)
}

kimber_test <- function(x) {
    .Call(`_exptest2_kimber_test`, x)
}

kochar_test <- function(x) {
    .Call(`_exptest2_kochar_test`, x)
}

ks_test <- function(x) {
    .Call(`_exptest2_ks_test`, x)
}

lorenz_test <- function(x, p = 0.5) {
    .Call(`_exptest2_lorenz_test`, x, p)
}

moran_test <- function(x) {
    .Call(`_exptest2_moran_test`, x)
}

pietra_test <- function(x) {
    .Call(`_exptest2_pietra_test`, x)
}

rossberg_test <- function(x) {
    .Call(`_exptest2_rossberg_test`, x)
}

shapiro_test <- function(x) {
    .Call(`_exptest2_shapiro_test`, x)
}

exp_test_integral <- function(x) {
    .Call(`_exptest2_exp_test_integral`, x)
}

exp_test_kolmogorov <- function(x) {
    .Call(`_exptest2_exp_test_kolmogorov`, x)
}

we_test <- function(x) {
    .Call(`_exptest2_we_test`, x)
}

ww_test <- function(x) {
    .Call(`_exptest2_ww_test`, x)
}

